# -*- coding: utf-8 -*-

# -*- mode: python -*-
#
# elf_diff
#
# Copyright (C) 2021  Noseglasses (shinynoseglasses@gmail.com)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

from elf_diff.plugin import ExportPairReportPlugin
from elf_diff.document_explorer import DocumentExplorer, TREE_TRAVERSAL_ALL
import yaml


class YAMLExportPairReportPlugin(ExportPairReportPlugin):
    def __init__(self, settings, plugin_configuration):
        super().__init__(settings, plugin_configuration)

    def export(self, document):
        dict_ = DocumentExplorer().generateDictionary(
            document, tree_traversal_options=TREE_TRAVERSAL_ALL
        )

        # import json
        # print(json.dumps(dict_, sort_keys=True, indent=4))

        yaml_output = yaml.dump(dict_, default_flow_style=False)

        with open(self.plugin_configuration["output_file"], "w") as f:
            f.write(
                """\
# This file was autogenerated with love by elf_diff %s
# for more information see
#    * https://github.com/noseglasses/elf_diff
#    * https://pypi.org/project/elf-diff/
"""
                % document.general.elf_diff_version
            )
            f.write(yaml_output)
