name: Deploy Examples

on:
  push:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Ubuntu packages
      run: |
         sudo apt install -y python3-pip
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r ./requirements.txt
    - name: Test
      run: |
        mkdir -p example_output/simple
        cd example_output/simple
        python3 ../../bin/elf_diff \
          --html_dir pair_report_multi_page \
          --old_binary ../../tests/x86_64/libelf_diff_test_debug_old.a \
          --new_binary ../../tests/x86_64/libelf_diff_test_debug_new.a \
          --old_source_prefix "src/old/" \
          --new_source_prefix "src/new/"
        python3 ../../bin/elf_diff \
          --html_file pair_report_output.html \
          --old_binary ../../tests/x86_64/libelf_diff_test_debug_old.a \
          --new_binary ../../tests/x86_64/libelf_diff_test_debug_new.a \
          --old_source_prefix "src/old/" \
          --new_source_prefix "src/new/"
    - name: Examples
      run: |
        mkdir -p example_output/simple2
        cd example_output/simple2
        python3 ../../bin/elf_diff \
          --html_dir pair_report_multi_page \
          --old_binary ../../tests/x86_64/libelf_diff_test2_debug_old.a \
          --new_binary ../../tests/x86_64/libelf_diff_test2_debug_new.a \
          --old_source_prefix "src/old/" \
          --new_source_prefix "src/new/"
        python3 ../../bin/elf_diff \
          --html_file pair_report_output.html \
          --old_binary ../../tests/x86_64/libelf_diff_test2_debug_old.a \
          --new_binary ../../tests/x86_64/libelf_diff_test2_debug_new.a \
          --old_source_prefix "src/old/" \
          --new_source_prefix "src/new/"
    - name: Prepare Example Deploy 1
      run: |
        mkdir -p example_deploy/examples/simple
        cd example_deploy/examples/simple
        cp -a ../../../example_output/simple/pair_report_multi_page .
        cp ../../../example_output/simple/pair_report_output.html .
    - name: Prepare Example Deploy 2
      run: |
        mkdir -p example_deploy/examples/simple2
        cd example_deploy/examples/simple2
        cp -a ../../../example_output/simple2/pair_report_multi_page .
        cp ../../../example_output/simple2/pair_report_output.html .
    - name: Prepare Index
      run: |
        mkdir -p example_deploy
        cd example_deploy
        cp ../src/elf_diff/html/example_page.html ./index.html
    - name: HTML Link Check
      uses: lycheeverse/lychee-action@v1.0.8
      id: lychee_html
      with:
        args: --verbose --no-progress "example_deploy/**/*.html"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Fail on HTML Link Check Errors
      run: exit ${{ steps.lychee_html.outputs.exit_code }}
    - name: Deploy To Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: ${{ github.event_name == 'push' }} # Only run on push to master (which only happens if a PR is merged)
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: /home/runner/work/elf_diff/elf_diff/example_deploy # The folder the action should deploy.
