name: PyPI Package Deploy

on:
  release:
    types: [published]

jobs:
  package_deploy:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: |
        python3 -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: |
        python3 -m build --sdist --wheel --outdir dist/
    - name: Check version tag
      run: |
        source scripts/validate_package_version.sh
        validate_package_version "${GITHUB_REF}"
    #- name: Publish distribution 📦 to Test PyPI
    #  uses: pypa/gh-action-pypi-publish@master
    #  with:
    #    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #    repository_url: https://test_main.pypi.org/legacy/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

