# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Ubuntu packages
      run: |
      #  sudo apt-get update
      #  sudo apt-get install -y wkhtmltopdf
      #  sudo apt-get install -y xvfb
         # For weasyprint
         sudo apt install -y python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest weasyprint
        if [ -f python/requirements.txt ]; then pip install -r python/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        #xvfb-run -a -s "-screen 0 640x480x16" python3 testing/test.py
        python3 testing/test.py
        python3 testing/test_cpp_symbols.py
