name: Type checking with mypy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  type_check:
    name: Type check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Ubuntu packages
      run: |
         sudo apt install -y python3-pip
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        python3 -m pip install mypy
    - name: Prepare mypy
      run: |
        python3 -m pip install types-PyYAML
    - name: Type check
      run: |
        python3 -m mypy .
