name: Local Package Install and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  local_package_install_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Ubuntu packages
      run: |
         sudo apt install -y python3-pip python3-venv
         sudo apt install -y g++-arm-linux-gnueabi binutils-arm-linux-gnueabi
    - name: Generate venv
      run: |
        repo_root=$PWD
        cd ..
        python3 -m venv env
        source ./env/bin/activate
        mkdir test
        cd test
        python3 -m pip install --upgrade pip
        python3 -m pip install -r "${repo_root}/tests/test_requirements.txt"
        python3 -m pip install "${repo_root}"
        python3 "${repo_root}/tests/test_main.py" -p
